default_platform(:android)

platform :android do
  desc "Build, test, and deploy the production version to Google Play"
  lane :deploy do
    gradle(task: "testDebugUnitTest")
    gradle(task: "clean :donextv2:bundleRelease")
    upload_to_play_store(
      track: "production",
      aab: "donextv2/build/outputs/bundle/release/donextv2-release.aab"
    )
  end

  desc "Build, test, and deploy to Google Play"
  lane :internal do
    gradle(task: "testDebugUnitTest")
    gradle(task: "clean :donextv2:bundleRelease")
    upload_to_play_store(
      track: "internal",
      aab: "donextv2/build/outputs/bundle/release/donextv2-release.aab"
    )
  end
end