default_platform(:android)

platform :android do
  desc "Run all unit tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  desc "Build a release APK or AAB for beta testing"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "beta",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Deploy the production version to Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
